SICP.IAModule = (function() {
  var _search = '';
  var _filtroComponente = '';
  var _filtroDificultad = '';
  var _filtroTipo = '';
  var _smartFilter = false;

  var TIPOS = ['redaccion','analisis','planificacion','gestion','evaluacion','creatividad','presentacion'];
  var DIFICULTADES = ['basico','intermedio','avanzado'];
  var COMPONENTES = ['C1','C2','C3','general'];

  function escape(s) { return SICP.utils.escapeHtml(s); }

  function getPerfil() {
    try {
      var perfil = SICP.db.getProfile();
      var conf = SICP.db.getConfig();
      var stats = SICP.db.calcularStats();
      return { perfil: perfil, conf: conf, stats: stats };
    } catch(e) { return null; }
  }

  function getCategorias(datos) {
    var p = datos ? datos.perfil : null;
    var c = datos ? datos.conf : null;
    var s = datos ? datos.stats : null;

    return [
      { nombre: 'Redacción científica avanzada', icon: '✍️', prompts: [
        { titulo: 'Estructurar artículo IMRyD completo', prompt: 'Eres editor senior de revista Scopus Q1 con 20 años de experiencia. Recibes el siguiente manuscrito sobre [TEMA].\n\nTu tarea:\n1. Evalúa si la estructura IMRyD está completa y balanceada (Introducción 20%, Métodos 25%, Resultados 30%, Discusión 25%).\n2. Identifica huecos en la argumentación.\n3. Sugiere títulos alternativos más atractivos y con palabras clave SEO académico.\n4. Verifica coherencia entre objetivo, hipótesis, métodos y conclusión.\n\nManuscrito:\n[PEGA AQUÍ TU TEXTO]\n\nFormato de respuesta: tabla con 4 columnas — Sección | Problema detectado | Sugerencia | Prioridad (Alta/Media/Baja).', tags: { componente: 'C1', tipo: 'redaccion', dificultad: 'intermedio' } },
        { titulo: 'Redactar título y resumen', prompt: 'Actúa como experto en comunicación científica. Necesito optimizar el título y resumen de mi artículo para maximizar citaciones e indexación.\n\nTítulo actual:\n[TÍTULO]\n\nResumen actual:\n[PEGA AQUÍ]\n\nCampo de estudio:\n[CAMPO]\n\nRevista objetivo:\n[REVISTA]\n\nGenera:\n1. 3 variantes de título (descriptivo, provocativo y orientado a palabras clave).\n2. Resumen reestructurado en 5 oraciones: contexto, gap, propósito, método, hallazgo clave e implicación.\n3. 6 palabras clave: 3 tradicionales y 3 emergentes/SEO.\n4. Plain language summary para difusión en acceso abierto (C3).', tags: { componente: 'C1', tipo: 'redaccion', dificultad: 'intermedio' } },
        { titulo: 'Carta al editor y rebuttal', prompt: 'Eres asesor de publicación académica. Ayúdame a preparar:\n\n1. Cover letter para mi artículo "[TÍTULO]" en "[REVISTA]": máximo 300 palabras. Menciona originalidad, relevancia para lectores de la revista y que no está sometido simultáneamente.\n\n2. Estrategia de rebuttal para revisores. Usa el formato: Comentario del revisor | Nuestra respuesta | Cambio realizado (línea: xx).\n\nComentarios recibidos:\n[PEGA AQUÍ]', tags: { componente: 'C1', tipo: 'redaccion', dificultad: 'avanzado' } },
        { titulo: 'Optimizar abstract para Scopus/WoS', prompt: 'Actúa como indexador de Scopus. Revisa el siguiente abstract y optimízalo para cumplir criterios de indexación:\n\n[PEGA AQUÍ]\n\nVerifica:\n- ¿Tiene estructura implícita (Background, Methods, Results, Conclusion)?\n- ¿Las palabras clave reflejan términos MeSH/ERIC/INSPEC?\n- ¿Cumple el límite de 250 palabras?\n- ¿Incluye datos cuantitativos relevantes?\n- ¿Evita jerga excesiva?\n\nProporciona versión mejorada y tabla de verificación.', tags: { componente: 'C1', tipo: 'evaluacion', dificultad: 'intermedio' } },
        { titulo: 'Revisión de literatura automatizada', prompt: 'Eres bibliotecólogo experto en revisiones sistemáticas. Ayúdame a diseñar una revisión de literatura sobre:\n\nTema: [TEMA]\nPregunta de investigación: [PREGUNTA]\nBases de datos: Scopus, WoS, PubMed, SciELO\n\nGenera:\n1. Ecuación de búsqueda booleana optimizada.\n2. Criterios PRISMA de inclusión/exclusión.\n3. Matriz de extracción de datos (autor, año, diseño, muestra, hallazgos, limitaciones).\n4. Diagrama de flujo PRISMA 2020 en texto.\n5. Identificación de 3-5 brechas en la literatura.', tags: { componente: 'C1', tipo: 'analisis', dificultad: 'avanzado' } },
        { titulo: 'Redactar discusión y conclusiones', prompt: 'Eres editor científico especializado en redacción de discusiones. Ayúdame a fortalecer esta sección:\n\nResultados principales:\n[LISTA TUS 3-5 HALLAZGOS]\n\nHipótesis inicial:\n[HIPÓTESIS]\n\nLiteratura relevante:\n[AUTORES Y AÑOS CLAVE]\n\nGenera una discusión que:\n1. Abra con el hallazgo más importante y su significado.\n2. Compare cada hallazgo con la literatura existente (confirma/contradice/extiende).\n3. Aborde limitaciones del estudio con honestidad intelectual.\n4. Proponga 3 líneas futuras concretas.\n5. Concluya con una oración que sintetice la contribución única.\n\nIncluye versión de conclusiones en 5 bullet points.', tags: { componente: 'C1', tipo: 'redaccion', dificultad: 'avanzado' } },
        { titulo: 'Traducción académica español-inglés', prompt: 'Eres traductor especializado en textos científicos con experiencia en revistas internacionales. Traduce y optimiza el siguiente texto para una audiencia internacional:\n\nTexto original (español):\n[PEGA AQUÍ]\n\nTipo de documento: [ARTÍCULO / ABSTRACT / PÓSTER / INFORME]\nRevista objetivo: [REVISTA EN INGLÉS]\n\nInstrucciones:\n1. Traducción natural (no literal) que preserve el significado técnico.\n2. Adapta la estructura de oraciones al estilo anglosajón (sujeto-verbo-objeto, voz activa).\n3. Sugiere 3 términos alternativos para conceptos clave.\n4. Señala falsos amigos y su corrección.\n5. Marca con [REVISAR] pasajes que requieren juicio del autor.', tags: { componente: 'C1', tipo: 'redaccion', dificultad: 'basico' } },
        { titulo: 'Generar citas y referencias', prompt: 'Eres gestor bibliográfico experto. Ayúdame con la gestión de referencias:\n\nLista de fuentes (títulos, autores o DOIs):\n[PEGA AQUÍ]\n\nFormato solicitado: [APA 7ª / VANCOUVER / IEEE / CHICAGO]\n\nGenera:\n1. Lista de referencias completa en el formato solicitado.\n2. Identificación de referencias incompletas (falta DOI, año, editorial).\n3. Verificación de consistencia (todos los autores citados en texto deben estar en referencias).\n4. Sugerencias para incluir referencias de alto impacto adicionales sobre [TEMA].', tags: { componente: 'general', tipo: 'gestion', dificultad: 'basico' } }
      ]},
      { nombre: 'Metodología y análisis', icon: '📊', prompts: [
        { titulo: 'Diseño metodológico integral', prompt: 'Eres metodólogo experto CONAHCYT-SECIHTI. Ayúdame a diseñar el apartado metodológico para:\n\nTema: [TEMA]\nTipo de estudio: [EXPLORATORIO / DESCRIPTIVO / CORRELACIONAL / EXPERIMENTAL]\nEnfoque: [CUALITATIVO / CUANTITATIVO / MIXTO]\n\nProporciona:\n1. Justificación del diseño elegido con referencias metodológicas.\n2. Descripción detallada de procedimientos paso a paso.\n3. Validez interna y externa.\n4. Limitaciones y estrategias de mitigación.\n5. Tabla de operacionalización de variables.', tags: { componente: 'C1', tipo: 'analisis', dificultad: 'intermedio' } },
        { titulo: 'Matriz de congruencia metodológica', prompt: 'Genera una matriz de congruencia para mi investigación. Formato tabla:\n\n| Pregunta investigación | Objetivo general | Hipótesis | Variables | Indicadores | Técnica | Instrumento |\n|---|---|---|---|---|---|---|\n\nTema: [TEMA]\nObjetivos: [OBJETIVOS]\n\nVerifica: cada objetivo debe responder a una pregunta; cada hipótesis debe contrastarse con una técnica específica.', tags: { componente: 'C1', tipo: 'planificacion', dificultad: 'intermedio' } },
        { titulo: 'Análisis cualitativo avanzado', prompt: 'Eres investigador cualitativo con experiencia en grounded theory y análisis temático. Para mi estudio sobre [TEMA]:\n\nDatos: [TRANSCRIPCIONES / NOTAS DE CAMPO / DOCUMENTOS]\nParticipantes: [NÚMERO Y PERFIL]\n\nGenera:\n1. Propuesta de sistema de categorías (10-15 códigos iniciales).\n2. Definición operacional de cada categoría.\n3. Matriz de codificación para Atlas.ti o NVivo.\n4. Posibles temas emergentes y su relación.\n5. Estrategia de saturación teórica.', tags: { componente: 'C1', tipo: 'analisis', dificultad: 'avanzado' } },
        { titulo: 'Análisis cuantitativo y poder estadístico', prompt: 'Eres bioestadístico senior. Revisa mi plan de análisis:\n\nTipo de datos: [CONTINUOS / CATEGÓRICOS / ORDINALES]\nTamaño de muestra: n=[N]\nVariables: dependiente=[VD], independiente=[VI], control=[VC]\nHipótesis: [HIPÓTESIS]\n\nResponde:\n1. ¿Qué prueba estadística es adecuada y por qué?\n2. ¿El tamaño de muestra tiene poder suficiente? Calcula poder para detectar efecto de [d=0.3 / d=0.5 / d=0.8].\n3. ¿Qué supuestos deben verificarse (normalidad, homocedasticidad)?\n4. Interpretación hipotética de resultados.\n5. Recomendaciones de visualización de datos.', tags: { componente: 'C1', tipo: 'analisis', dificultad: 'avanzado' } },
        { titulo: 'Métodos mixtos (diseño convergente)', prompt: 'Diseña un estudio de métodos mixtos con diseño convergente paralelo para:\n\nComponente cuantitativo: [ENCUESTA / EXPERIMENTO]\nComponente cualitativo: [ENTREVISTAS / GRUPOS FOCALES]\nPregunta integradora: [PREGUNTA]\n\nIncluye:\n1. Diagrama de procedimiento (CUAN → cual / cual → CUAN).\n2. Estrategia de integración de datos (joint display).\n3. Matriz de meta-inferencias.\n4. Validación de la integración (legitimización).', tags: { componente: 'C1', tipo: 'planificacion', dificultad: 'avanzado' } },
        { titulo: 'Diseño de instrumentos de investigación', prompt: 'Eres metodólogo especializado en diseño de instrumentos. Ayúdame a crear:\n\nTipo: [ENCUESTA / GUÍA DE ENTREVISTA / RÚBRICA / LISTA COTEJO]\nTema: [TEMA]\nPoblación: [PERFIL DE PARTICIPANTES]\n\nGenera:\n1. 10-15 ítems o preguntas alineadas a los objetivos.\n2. Escala de medición recomendada (Likert, diferencial semántico, nominal).\n3. Tabla de especificaciones: dimensión | indicador | ítem | peso.\n4. Instrucciones claras para el aplicador.\n5. Estrategia de validación (juicio de expertos, piloto, alpha de Cronbach).', tags: { componente: 'C1', tipo: 'planificacion', dificultad: 'intermedio' } },
        { titulo: 'Protocolo de investigación completo', prompt: 'Redacta un protocolo de investigación para:\n\nTítulo: [TÍTULO]\nTipo: [TESIS / PROYECTO / ESTANCIA]\nPlazo: [MESES]\n\nIncluye:\n1. Planteamiento del problema (contexto, gap, pregunta).\n2. Justificación (teórica, práctica, metodológica).\n3. Marco teórico (principales autores y corrientes).\n4. Hipótesis u objetivos.\n5. Método (diseño, muestra, instrumentos, procedimiento, análisis).\n6. Cronograma en diagrama Gantt.\n7. Referencias clave (10-15).\n8. Anexos (instrumentos piloto, carta consentimiento).', tags: { componente: 'C1', tipo: 'planificacion', dificultad: 'intermedio' } },
        { titulo: 'Análisis de datos cualitativos con IA', prompt: 'Eres analista cualitativo experto en IA. Ayúdame a procesar datos cualitativos:\n\nDatos:\n[PEGA TRANSCRIPCIONES O RESPUESTAS ABIERTAS]\n\nTécnica: [ANÁLISIS TEMÁTICO / TEORÍA FUNDAMENTADA / ANÁLISIS CONTENIDO]\n\nUtiliza IA para:\n1. Identificar patrones y temas emergentes automáticamente.\n2. Generar nubes de palabras clave del discurso.\n3. Crear matriz de co-ocurrencia de categorías.\n4. Extraer citas representativas por tema.\n5. Proponer narrativa integradora de hallazgos.', tags: { componente: 'C1', tipo: 'analisis', dificultad: 'avanzado' } }
      ]},
      { nombre: 'Gestión SNII 2026', icon: '🏆', prompts: [
        { titulo: 'Auditar expediente SNII completo', prompt: 'Actúa como evaluador SNII 2026 designado por SECIHTI. Revisa mi expediente:\n\nÁrea: [' + escape(p ? p.area || '[ÁREA]' : '[ÁREA]') + ']\nPerfil: [' + escape(p ? p.perfilInvestigacion || '[PERFIL]' : '[PERFIL]') + ']\nProductos registrados: ' + (s ? s.totalProductos : '[N]') + ' (C1:' + (s ? s.componente1 : '[N]') + '%, C2:' + (s ? s.componente2 : '[N]') + '%, C3:' + (s ? s.componente3 : '[N]') + '%)\n\n' + (s && s.brechas.length > 0 ? 'Brechas detectadas:\n' + s.brechas.map(function(b) { return '- ' + b.area + ': ' + b.actual + '/' + b.meta; }).join('\n') : '') + '\n\nClasifica cada producto en C1/C2/C3 según Anexos. Identifica:\n1. Falsos positivos (productos mal clasificados).\n2. Evidencias faltantes por producto.\n3. Recomendaciones priorizadas por componente.', tags: { componente: 'general', tipo: 'evaluacion', dificultad: 'avanzado' } },
        { titulo: 'Plan anual por componentes', prompt: 'Diseña un plan anual personalizado para fortalecer mi perfil SNII 2026:\n\nPerfil: [' + escape(p ? p.perfilInvestigacion || '[PERFIL]' : '[PERFIL]') + ']\nÁrea: [' + escape(p ? p.area || '[ÁREA]' : '[ÁREA]') + ']\nScore actual: ' + (s ? s.scoreSNII + '%' : '[SCORE]') + '\nComponentes: C1=' + (s ? s.componente1 + '%' : '[N]') + ', C2=' + (s ? s.componente2 + '%' : '[N]') + ', C3=' + (s ? s.componente3 + '%' : '[N]') + '\n\nGenera un plan trimestral con:\n- Metas específicas por componente.\n- Productos a desarrollar por trimestre.\n- Evidencias a recolectar.\n- Horas semanales estimadas.\n- Hitos críticos y fechas sugeridas.\nFormato: tabla con columnas Trimestre | Componente | Acción | Producto esperado | Evidencia | Prioridad.', tags: { componente: 'general', tipo: 'planificacion', dificultad: 'intermedio' } },
        { titulo: 'Narrativa académica alineada al perfil', prompt: 'Redacta mi narrativa para la solicitud SNII 2026. Debe convencer al evaluador de que mi trayectoria encaja en el perfil seleccionado.\n\nPerfil: [' + escape(p ? p.perfilInvestigacion || '[PERFIL]' : '[PERFIL]') + ']\nÁrea SNII: [' + escape(p ? p.area || '[ÁREA]' : '[ÁREA]') + ']\nLínea de investigación: [' + escape(p ? p.lineaInvestigacion || '[LÍNEA]' : '[LÍNEA]') + ']\n\nProductos principales:\n' + (function(){ try { return SICP.db.getProductos().slice(0,5).map(function(pr){ return '- ' + escape(pr.titulo) + ' (' + escape(pr.tipo) + ', ' + (pr.anno||'s/f') + ')'; }).join('\n'); } catch(e){ return '- [LISTA TUS 5 PRODUCTOS MÁS IMPORTANTES]'; } })() + '\n\nEstructura:\n1. Síntesis de trayectoria (3 líneas).\n2. Aportaciones originales (C1).\n3. Fortalecimiento de la comunidad HCTI (C2).\n4. Acceso universal al conocimiento (C3).\n5. Prospectiva 2026-2029 (próximos pasos).\nMáximo 500 palabras. Tono: formal pero convincente.', tags: { componente: 'general', tipo: 'redaccion', dificultad: 'intermedio' } },
        { titulo: 'Diagnóstico con Anexos 1-4', prompt: 'Actúa como analista de criterios SECIHTI. Aplica los parámetros de los Anexos 1-4 a mi perfil:\n\nÁrea: [' + escape(p ? p.area || '[ÁREA]' : '[ÁREA]') + ']\nPerfil: [' + escape(p ? p.perfilInvestigacion || '[PERFIL]' : '[PERFIL]') + ']\nNivel SNII actual: [' + escape(p ? p.nivelActual || '[NIVEL]' : '[NIVEL]') + ']\n\n' + (function(){ try { var pros = SICP.db.getProductos(); if(pros.length===0) return 'Productos: [LISTA TUS PRODUCTOS CON TIPO Y AÑO]'; return pros.map(function(pr){ return '- ' + escape(pr.titulo) + ' | ' + escape(pr.tipo) + ' | ' + (pr.anno||'s/f'); }).join('\n'); } catch(e){ return 'Productos: [LISTA TUS PRODUCTOS]'; } })() + '\n\nEvalúa:\n1. Puntuación estimada por tipo de producto (según Anexo 1).\n2. Nivel TRL para productos de innovación (Anexo 2).\n3. Suficiencia de evidencias probatorias (Anexo 4).\n4. Brechas específicas basadas en umbrales del área.\n5. Recomendación: ¿postular este año o esperar?', tags: { componente: 'general', tipo: 'evaluacion', dificultad: 'avanzado' } },
        { titulo: 'Estrategia de postulación Ápeiron', prompt: 'Eres experto en el Sistema Informático Ápeiron de SECIHTI. Guíame paso a paso:\n\n1. Pre-registro: documentos necesarios (identificación, constancia de adscripción, CV Único de Rizoma actualizado).\n2. Captura de productos: orden recomendado, clasificación por componente.\n3. Subida de evidencias: formatos aceptados (PDF, JPG, MP4), tamaño máximo, organización por Anexo.\n4. Validación: lista de verificación previa al envío.\n5. Seguimiento: tiempos de dictamen, posibilidad de subsanación.\n\nMi perfil:\n- Nombre: [' + escape(p ? p.nombre || '[NOMBRE]' : '[NOMBRE]') + ']\n- Nivel actual: [' + escape(p ? p.nivelActual || '[NIVEL]' : '[NIVEL]') + ']\n- Productos a registrar: ' + (s ? s.totalProductos + ' (' + s.articulos + ' artículos, ' + s.libros + ' libros)' : '[CANTIDAD]'), tags: { componente: 'general', tipo: 'gestion', dificultad: 'basico' } },
        { titulo: 'Análisis comparativo de perfiles', prompt: 'Analiza mi trayectoria y recomiéndame el perfil SNII 2026 más adecuado:\n\nMis productos:\n' + (function(){ try { var pros = SICP.db.getProductos(); if(pros.length===0) return '[LISTA TUS PRODUCTOS]'; var grupos = {}; pros.forEach(function(pr){ grupos[pr.tipo] = (grupos[pr.tipo]||0)+1; }); return Object.keys(grupos).map(function(k){ return '- ' + k + ': ' + grupos[k]; }).join('\n'); } catch(e){ return '[LISTA TUS PRODUCTOS]'; } })() + '\n\nLínea de investigación: [' + escape(p ? p.lineaInvestigacion || '[LÍNEA]' : '[LÍNEA]') + ']\n\nCompara los 4 perfiles:\nA) Ciencia básica y de frontera — prioriza artículos, libros, redes.\nB) Desarrollo tecnológico e innovación — prioriza patentes, software, TRL.\nC) Atención a problemas nacionales — prioriza impacto social, vinculación.\nD) Interdisciplinaria — prioriza integración multi-área.\n\nPara cada perfil: (1) afinidad con tu trayectoria, (2) fortalezas actuales, (3) debilidades a cubrir, (4) probabilidad estimada de éxito.', tags: { componente: 'general', tipo: 'evaluacion', dificultad: 'intermedio' } },
        { titulo: 'Calculadora de puntuación SNII', prompt: 'Actúa como analista cuantitativo de criterios SNII. Con base en mis productos, calcula mi puntuación estimada:\n\nPerfil: [' + escape(p ? p.perfilInvestigacion || '[PERFIL]' : '[PERFIL]') + ']\nArtículos: ' + (s ? s.articulos : '[N]') + ' (ponderación: ' + (c ? c.ponderacionArticulos||12 : 12) + ' pts c/u)\nLibros: ' + (s ? s.libros : '[N]') + ' (pond: ' + (c ? c.ponderacionLibros||7 : 7) + ')\nTesis: ' + (s ? s.tesis : '[N]') + ' (pond: ' + (c ? c.ponderacionTesis||6 : 6) + ')\nInnovación: ' + (s ? s.innovacion : '[N]') + ' (pond: ' + (c ? c.ponderacionInnovacion||7 : 7) + ')\nLiderazgo: ' + (s ? s.liderazgo : '[N]') + ' (pond: ' + (c ? c.ponderacionLiderazgo||5 : 5) + ')\nDivulgación: ' + (s ? s.divulgacion : '[N]') + ' (pond: ' + (c ? c.ponderacionDivulgacion||3 : 3) + ')\n\nCalcula:\n1. Puntuación bruta por componente.\n2. Puntuación ponderada con pesos ' + (c ? (c.ponderacionComponente1||40) : 40) + '/' + (c ? (c.ponderacionComponente2||30) : 30) + '/' + (c ? (c.ponderacionComponente3||30) : 30) + '.\n3. Score SNII final.\n4. Productos faltantes para alcanzar [NIVEL META] emulando escenarios.', tags: { componente: 'general', tipo: 'analisis', dificultad: 'intermedio' } },
        { titulo: 'Preparación para entrevista con evaluadores', prompt: 'Eres evaluador SNII con 10 años de experiencia. Prepárame para una entrevista de defensa de mi solicitud:\n\nMi perfil:\n- Nombre: [' + escape(p ? p.nombre || '[NOMBRE]' : '[NOMBRE]') + ']\n- Área: [' + escape(p ? p.area || '[ÁREA]' : '[ÁREA]') + ']\n- Perfil: [' + escape(p ? p.perfilInvestigacion || '[PERFIL]' : '[PERFIL]') + ']\n- Nivel al que aspiro: [' + escape(p ? p.metaSNII || '[NIVEL]' : '[NIVEL]') + ']\n\nGenera:\n1. Las 10 preguntas más probables en la entrevista.\n2. Respuestas modelo con estructura STAR (Situación, Tarea, Acción, Resultado).\n3. 3 fortalezas que debo destacar.\n4. 2 debilidades y cómo presentarlas sin afectar mi candidatura.\n5. Preguntas inteligentes que puedo hacer al evaluador.', tags: { componente: 'general', tipo: 'presentacion', dificultad: 'avanzado' } }
      ]},
      { nombre: 'Tesis y formación de RRHH', icon: '🎓', prompts: [
        { titulo: 'Diseñar plan de tesis completo', prompt: 'Eres director de tesis con 30 tesis tituladas. Diseña un plan de trabajo detallado para:\n\nNivel: [LICENCIATURA / MAESTRÍA / DOCTORADO]\nTema: [TEMA]\nEstudiante: [NOMBRE] (tiempo completo / parcial)\nPlazo: [MESES]\n\nIncluye:\n1. Cronograma Gantt por fase (Investigación | Desarrollo | Redacción | Revisión | Defensa).\n2. Hitos con entregables concretos (protocolo, avance, borrador, artículo derivado).\n3. Sesiones de tutoría programadas (cada 15 días).\n4. Bibliografía mínima y complementaria.\n5. Ruta para generar 1 producto SNII derivado (artículo o congreso).\n6. Carta de liberación de tema para expediente del tesista.', tags: { componente: 'C2', tipo: 'planificacion', dificultad: 'intermedio' } },
        { titulo: 'Retroalimentación estructurada de tesis', prompt: 'Actúa como revisor de tesis experto. Proporciona retroalimentación estructurada:\n\n[PEGA AQUÍ EL AVANCE]\nNivel: [LICENCIATURA / MAESTRÍA / DOCTORADO]\n\nEvalúa con semáforo:\n🔴 Crítico (debe corregirse)\n🟡 Sugerencia (mejorable)\n🟢 Correcto\n\nCriterios:\n1. Claridad del planteamiento del problema.\n2. Coherencia entre objetivos, hipótesis y método.\n3. Suficiencia y pertinencia del marco teórico.\n4. Rigor metodológico.\n5. Redacción y estilo académico.\n6. Aportación original observada.', tags: { componente: 'C2', tipo: 'evaluacion', dificultad: 'intermedio' } },
        { titulo: 'Reporte de formación para expediente SNII', prompt: 'Genera un reporte de actividades de formación académica para mi expediente SNII 2026 (C2: Formación de RRHH):\n\nTesis dirigidas:\n' + (function(){ try { return SICP.db.getProductos().filter(function(pr){ return pr.tipo === 'Tesis'; }).map(function(t){ return '- ' + escape(t.titulo) + ' (' + (t.anno||'s/f') + ')'; }).join('\n') || '[LISTA TUS TESIS]'; } catch(e){ return '[LISTA TUS TESIS]'; } })() + '\n\nDocencia: [ASIGNATURAS, HORAS, PROGRAMAS]\n\nEstructura del reporte:\n1. Resumen ejecutivo de actividades de formación (5 líneas).\n2. Tabla de tesis dirigidas: Estudiante | Nivel | Título | Estado (titulada/proceso) | Fecha examen.\n3. Productos derivados de tesis (artículos, congresos).\n4. Impacto en el componente C2.', tags: { componente: 'C2', tipo: 'gestion', dificultad: 'intermedio' } },
        { titulo: 'Guía para codirección de tesis', prompt: 'Actúa como especialista en colaboración académica. Diseña un acuerdo de codirección de tesis:\n\nTema: [TEMA]\nCodirector: [NOMBRE E INSTITUCIÓN]\nNivel: [MAESTRÍA / DOCTORADO]\n\nIncluye:\n1. Distribución de responsabilidades (tutoría metodológica, disciplinaria, experimental).\n2. Plan de comunicación y reuniones conjuntas.\n3. Política de autoría en publicaciones derivadas.\n4. Criterios de resolución de controversias.\n5. Carta-compromiso modelo firmable.', tags: { componente: 'C2', tipo: 'gestion', dificultad: 'basico' } },
        { titulo: 'Diseño de cursos y programas educativos', prompt: 'Eres diseñador instruccional. Ayúdame a diseñar el programa de una asignatura:\n\nNombre: [NOMBRE]\nNivel: [LICENCIATURA / MAESTRÍA]\nDuración: [SEMANAS]\n\nIncluye:\n1. Competencias a desarrollar (genéricas y específicas).\n2. Temario desglosado por unidad con horas teóricas/prácticas.\n3. Estrategias de enseñanza-aprendizaje (ABP, estudio caso, aprendizaje invertido).\n4. Sistema de evaluación con rúbricas.\n5. Bibliografía básica y complementaria.\n6. Producto integrador que pueda convertirse en evidencia C2.', tags: { componente: 'C2', tipo: 'planificacion', dificultad: 'intermedio' } },
        { titulo: 'Estrategia para aumento de titulación', prompt: 'Eres coordinador de posgrado. Diseña una estrategia para aumentar la titulación de mis tesistas:\n\nNúmero actual de tesistas: [N]\nTasa de titulación actual: [%]\nPrincipales causas de retraso: [FALTA TIEMPO / PROBLEMAS METODOLÓGICOS / BLOQUEO ESCRITURA]\n\nPropón:\n1. Sistema de hitos trimestrales con entregables mínimos.\n2. Talleres de escritura académica y método.\n3. Mentores pares entre tesistas.\n4. Calendario de exámenes de grado programados.\n5. Formato de carta-compromiso para nuevo tesista.\n6. Indicadores de seguimiento para tabla del director.', tags: { componente: 'C2', tipo: 'gestion', dificultad: 'intermedio' } },
        { titulo: 'Evaluación de programa de tutoría', prompt: 'Eres evaluador de programas educativos. Diseña un sistema de evaluación para mi programa de tutorías:\n\nNúmero de tutorados: [N]\nPeriodo: [SEMESTRE / AÑO]\nModalidad: [INDIVIDUAL / GRUPAL / MIXTA]\n\nGenera:\n1. Encuesta de satisfacción (10 preguntas escala Likert).\n2. Rúbrica de desempeño tutorial (5 criterios).\n3. Indicadores de efectividad (retención, titulación, productividad).\n4. Formato de reporte semestral de tutoría.\n5. Plan de mejora basado en resultados.', tags: { componente: 'C2', tipo: 'evaluacion', dificultad: 'basico' } }
      ]},
      { nombre: 'Productividad científica', icon: '⚡', prompts: [
        { titulo: 'Plan semanal inteligente (15h)', prompt: 'Diseña un plan semanal personalizado de 15 horas para investigador SNII:\n\n' + (s ? 'Score actual: ' + s.scoreSNII + '% (C1=' + s.componente1 + ', C2=' + s.componente2 + ', C3=' + s.componente3 + ')\n' : '') + 'Brechas: ' + (s && s.brechas.length > 0 ? s.brechas.map(function(b){ return b.area; }).join(', ') : '[TUS BRECHAS]') + '\n\nDistribuye el tiempo priorizando las brechas detectadas:\nLunes-Viernes en bloques de 1-3h.\nIncluye: lectura, escritura, análisis, evidencias, vinculación, y descanso activo.\nFormato: tabla con Día | Bloque horario | Actividad | Resultado esperado | Componente SNII.', tags: { componente: 'general', tipo: 'planificacion', dificultad: 'basico' } },
        { titulo: 'De docencia a productos SNII', prompt: 'Analiza mis asignaturas y genera productos científicos derivados:\n\nAsignaturas impartidas:\n[LISTA TUS ASIGNATURAS]\n\nTipo de productos solicitados:\n1. Artículo didáctico — de una innovación en el aula.\n2. Material educativo con ISBN — guía, antología o cuaderno.\n3. Reporte de experiencia educativa — para congreso de docencia.\n4. Proyecto de investigación educativa — con metodología y resultados.\n5. Evidencia probatoria C2 — constancias, programas, diseño instruccional.', tags: { componente: 'C2', tipo: 'creatividad', dificultad: 'intermedio' } },
        { titulo: 'Sistema de carpetas para evidencias', prompt: 'Propón una estructura de carpetas digitales para organizar mis evidencias SNII optimizada para postulación en Ápeiron:\n\nEstructura sugerida:\n📁 SNII_2026/\n├── 📁 00_Documentos personales/\n├── 📁 C1_Produccion/ (Articulos, Libros, Innovacion, Proyectos)\n├── 📁 C2_Comunidad_HCTI/ (Tesis, Liderazgo, Docencia)\n├── 📁 C3_Acceso_Universal/ (Repositorios, Divulgacion, Metricas)\n└── 📁 Postulacion/ (narrativa, cronograma, formatos)\n\nExplica nombrado sugerido, metadatos mínimos y backup.', tags: { componente: 'general', tipo: 'gestion', dificultad: 'basico' } },
        { titulo: 'Automatización de búsquedas bibliográficas', prompt: 'Eres especialista en recuperación de información. Diseña un sistema de alertas bibliográficas automatizadas:\n\nTemas de interés:\n[LISTA DE 3-5 TEMAS]\n\nBases de datos: Scopus, WoS, PubMed, Google Scholar, SciELO\n\nGenera:\n1. Ecuaciones de búsqueda guardables para cada base.\n2. Configuración de alertas por correo semanales.\n3. Uso de operadores booleanos, paréntesis, truncamiento y filtros.\n4. Estrategia de almacenamiento en Zotero con etiquetas automáticas.\n5. Flujo semanal de revisión (triage de 30 min/semana).', tags: { componente: 'C1', tipo: 'gestion', dificultad: 'intermedio' } },
        { titulo: 'Técnicas de escritura acelerada', prompt: 'Eres coach de escritura académica. Diseña un programa de 4 semanas para escribir un artículo:\n\nTema: [TEMA]\nRevista objetivo: [REVISTA]\nExtensión: [PALABRAS]\n\nSemana 1: Outline + referencias (estructura, 20 referencias clave).\nSemana 2: Métodos + Resultados (escribe las partes más fáciles primero).\nSemana 3: Introducción + Discusión (conecta hallazgos con literatura).\nSemana 4: Resumen + pulido + formato revista.\n\nIncluye: técnicas de bloqueo de tiempo, pomodoro académico, y checklist de auto-revisión antes de someter.', tags: { componente: 'C1', tipo: 'redaccion', dificultad: 'basico' } },
        { titulo: 'Gestión de proyectos de investigación', prompt: 'Eres PMP certificado especializado en proyectos académicos. Ayúdame a gestionar:\n\nProyecto: [TÍTULO]\nDuración: [MESES]\nEquipo: [N] investigadores, [N] estudiantes\n\nImplementa:\n1. EDT (Estructura de Desglose de Trabajo) del proyecto.\n2. Matriz RACI de responsabilidades.\n3. Cronograma con ruta crítica.\n4. Presupuesto por rubro (equipo, viajes, materiales, publicación OA).\n5. Registro de riesgos con matriz de probabilidad-impacto.\n6. Dashboard de avance para reportes trimestrales al financiador.', tags: { componente: 'C1', tipo: 'planificacion', dificultad: 'avanzado' } }
      ]},
      { nombre: 'Liderazgo y redes', icon: '🤝', prompts: [
        { titulo: 'Estrategia de liderazgo académico', prompt: 'Propón 12 acciones concretas para fortalecer mi liderazgo académico en los próximos 12 meses orientadas al C2:\n\nÁrea: [' + escape(p ? p.area || '[ÁREA]' : '[ÁREA]') + ']\n' + (s ? 'Liderazgo actual: ' + s.liderazgo + ' actividades\n' : '') + '\n\nClasifica las acciones en:\n- Corto plazo (1-3 meses): comités, revisión de pares.\n- Mediano plazo (4-8 meses): conferencias magistrales, proyectos colaborativos.\n- Largo plazo (9-12 meses): redes interinstitucionales, premios.\n\nCada acción debe incluir: qué hacer, cómo documentarlo como evidencia C2, y expected impact.', tags: { componente: 'C2', tipo: 'planificacion', dificultad: 'intermedio' } },
        { titulo: 'Propuesta de red de investigación', prompt: 'Diseña una propuesta para crear una red de investigación sobre:\n\nTema: [TEMA]\nCoordinador: [' + escape(p ? p.nombre || '[NOMBRE]' : '[NOMBRE]') + ']\nInstituciones potenciales: [LISTA]\n\nFormato:\n1. Nombre y siglas de la red.\n2. Objetivos general y específicos.\n3. Miembros fundadores y roles.\n4. Plan de trabajo primer año (reuniones, productos, financiamiento).\n5. Estrategia de sostenibilidad.\n6. Proyecto piloto para financiamiento inicial.\n7. Indicadores de éxito.', tags: { componente: 'C2', tipo: 'planificacion', dificultad: 'avanzado' } },
        { titulo: 'Optimizar perfiles digitales', prompt: 'Redacta y optimiza mi declaración de investigación para:\n\n1. ORCID — resumen de investigación en 3-4 líneas + palabras clave.\n2. Google Scholar — breve bio académica (2 líneas).\n3. ResearchGate — declaración de intereses de investigación.\n4. Perfil Único de Rizoma — síntesis de trayectoria (5 líneas máximo).\n\nNombre: [' + escape(p ? p.nombre || '[NOMBRE]' : '[NOMBRE]') + ']\nLínea: [' + escape(p ? p.lineaInvestigacion || '[LÍNEA]' : '[LÍNEA]') + ']\nPerfil SNII: [' + escape(p ? p.perfilInvestigacion || '[PERFIL]' : '[PERFIL]') + ']', tags: { componente: 'general', tipo: 'redaccion', dificultad: 'basico' } },
        { titulo: 'Discurso para conferencia magistral', prompt: 'Eres coach de oratoria académica. Ayúdame a preparar una conferencia magistral:\n\nTítulo: [TÍTULO]\nEvento: [NOMBRE DEL CONGRESO]\nDuración: [MINUTOS]\nAudiencia: [ESPECIALISTAS / PÚBLICO MIXTO / ESTUDIANTES]\n\nGenera:\n1. Estructura de la presentación (gancho inicial | 3 ideas fuerza | cierre memorable).\n2. Timeline con minutos asignados por sección.\n3. 3 posibles preguntas del público y respuestas preparadas.\n4. Diapositivas clave sugeridas (máximo 10).\n5. Técnicas de storytelling académico.\n6. Recursos retóricos para mantener atención.', tags: { componente: 'C2', tipo: 'presentacion', dificultad: 'intermedio' } },
        { titulo: 'Carta de recomendación y nominación', prompt: 'Redacta una carta de recomendación académica sólida para:\n\nCandidato: [NOMBRE]\nPropósito: [PREmIO / BECA / POSGRADO / PUESTO ACADÉMICO]\nMi relación con el candidato: [DIRECTOR DE TESIS / COLABORADOR / PROFESOR]\n\nLa carta debe:\n1. Abrir con una declaración contundente de respaldo.\n2. Describir 2-3 logros específicos con datos concretos.\n3. Incluir comparación implícita con pares (percentil).\n4. Mencionar cualidades únicas (liderazgo, perseverancia, creatividad).\n5. Cerrar con ofrecimiento de ampliar información.\n\nTono: entusiasta pero objetivo, máx. 400 palabras.', tags: { componente: 'C2', tipo: 'redaccion', dificultad: 'intermedio' } },
        { titulo: 'Organización de evento académico', prompt: 'Eres coordinador de eventos académicos. Diseña el plan para organizar:\n\nTipo: [CONGRESO / SEMINARIO / TALLER / SIMPOSIO]\nTema: [TEMA]\nDuración: [DÍAS]\nParticipantes esperados: [N]\n\nIncluye:\n1. Comité organizador y comité científico (roles).\n2. Convocatoria de resúmenes y fechas clave.\n3. Programa tentativo (conferencias, mesas, pósters).\n4. Presupuesto estimado e identificación de patrocinadores.\n5. Estrategia de difusión (correo, redes, flyer).\n6. Libro de resúmenes con ISBN como producto C2.\n7. Encuesta de satisfacción posterior.', tags: { componente: 'C2', tipo: 'planificacion', dificultad: 'avanzado' } }
      ]},
      { nombre: 'Divulgación y ciencia abierta', icon: '🌐', prompts: [
        { titulo: 'Plan de divulgación científica (C3)', prompt: 'Diseña un plan de divulgación anual para fortalecer mi Componente 3 (Acceso universal al conocimiento):\n\nÁrea: [' + escape(p ? p.area || '[ÁREA]' : '[ÁREA]') + ']\nTemas: [' + escape(p ? p.lineaInvestigacion || '[TUS TEMAS]' : '[TUS TEMAS]') + ']\n' + (s ? 'Divulgación actual: ' + s.divulgacion + ' actividades\n' : '') + '\n\nGenera un calendario de 12 meses con:\n- 1 artículo de divulgación por trimestre (tema, medio, extensión).\n- 1 participación en feria de ciencia o semana académica.\n- 1 material educativo abierto (infografía, video, podcast).\n- Estrategia de repositorios abiertos para cada producto.\n- Métricas de alcance a reportar (visitas, descargas, menciones).\n- Formato tabla con mes | actividad | producto entregable | evidencia C3.', tags: { componente: 'C3', tipo: 'planificacion', dificultad: 'intermedio' } },
        { titulo: 'Resumen de divulgación (plain language)', prompt: 'Eres comunicador científico. Convierte el siguiente texto académico en:\n\nTexto original:\n[PEGA AQUÍ TU ARTÍCULO O ABSTRACTO]\n\n1. Resumen de divulgación (150 palabras, vocabulario accesible, sin jerga).\n2. Explicación en 3 tweets (280 caracteres c/u).\n3. Gancho para redes sociales (1 oración impactante).\n4. Preguntas frecuentes (FAQ) estilo entrevista de divulgación.\n5. Versión para repositorio abierto con descriptores de accesibilidad.', tags: { componente: 'C3', tipo: 'redaccion', dificultad: 'intermedio' } },
        { titulo: 'Material educativo abierto', prompt: 'Diseña un material educativo abierto sobre:\n\nTema: [TEMA]\nFormato: [INFOGRAFÍA / VIDEO / PODCAST / GUÍA]\nAudiencia: [PÚBLICO GENERAL / ESTUDIANTES / PROFESIONALES]\n\nIncluye:\n1. Storyboard o estructura del contenido.\n2. Guión narrativo o texto base.\n3. Elementos visuales sugeridos.\n4. Licencia Creative Commons recomendada.\n5. Metadatos para repositorio (DOI, palabras clave, fecha).\n6. Rúbrica de evaluación de efectividad comunicativa.', tags: { componente: 'C3', tipo: 'creatividad', dificultad: 'intermedio' } },
        { titulo: 'Estrategia de repositorios abiertos', prompt: 'Eres experto en ciencia abierta. Diseña una estrategia para maximizar mi presencia en repositorios:\n\nMis productos:\n' + (function(){ try { var pros = SICP.db.getProductos(); if(pros.length===0) return '[LISTA TUS PRODUCTOS CON DOI]'; return pros.slice(0,8).map(function(pr){ return '- ' + escape(pr.titulo) + ' (' + (pr.doi||'sin DOI') + ')'; }).join('\n'); } catch(e){ return '[LISTA TUS PRODUCTOS CON DOI]'; } })() + '\n\nGenera:\n1. Mapa de repositorios recomendados por tipo de producto (institucional, temático, multidisciplinario).\n2. Política de derechos de autor (verificar acuerdo editorial).\n3. Versiones permitidas: preprint / postprint / editor PDF.\n4. Metadatos mínimos por tipo de producto.\n5. Cronograma de depósito (1 producto/semana).\n6. Dashboard de seguimiento con indicadores de acceso abierto.', tags: { componente: 'C3', tipo: 'gestion', dificultad: 'intermedio' } },
        { titulo: 'Nota de prensa científica', prompt: 'Eres relacionista público especializado en comunicación de la ciencia. Redacta una nota de prensa sobre:\n\nHallazgo:\n[DESCRIPCIÓN DEL RESULTADO EN 3 LÍNEAS]\n\nInstitución: [' + escape(p ? p.institucion || '[INSTITUCIÓN]' : '[INSTITUCIÓN]') + ']\nInvestigador: [' + escape(p ? p.nombre || '[NOMBRE]' : '[NOMBRE]') + ']\n\nLa nota debe incluir:\n1. Titular atractivo (máx. 15 palabras, sin jerga).\n2. Lead que responda qué, quién, cuándo, dónde, por qué importa.\n3. Declaración textual del investigador (2-3 oraciones).\n4. Contexto y relevancia social del hallazgo.\n5. Datos de contacto para medios.\n6. Sugerencia de 2 imágenes o gráficos que acompañen.', tags: { componente: 'C3', tipo: 'redaccion', dificultad: 'basico' } },
        { titulo: 'Métrica de impacto social (altmetrics)', prompt: 'Eres analista de impacto académico. Diseña un informe de altmetrics para:\n\nProductos:\n' + (function(){ try { return SICP.db.getProductos().slice(0,5).map(function(pr){ return '- ' + escape(pr.titulo); }).join('\n'); } catch(e){ return '[LISTA TUS PUBLICACIONES]'; } })() + '\n\nGenera un tablero con:\n1. Altmetric Attention Score estimado por producto.\n2. Menciones en redes sociales, noticias, políticas públicas.\n3. Descargas y visualizaciones en repositorios.\n4. Comparativa con el promedio del área.\n5. Estrategia para aumentar visibilidad (fechas, redes, colaboraciones).\n6. Reporte exportable para incluir en expediente C3.', tags: { componente: 'C3', tipo: 'evaluacion', dificultad: 'avanzado' } }
      ]},
      { nombre: 'Proyectos y financiamiento', icon: '💰', prompts: [
        { titulo: 'Perfil de proyecto CONAHCYT/SECIHTI', prompt: 'Eres asesor de financiamiento científico. Ayúdame a redactar un perfil de proyecto para convocatoria SECIHTI:\n\nTítulo: [TÍTULO]\nDuración: [MESES]\nMonto solicitado: [MONTO]\nInstituciones participantes: [LISTA]\n\nEstructura:\n1. Resumen ejecutivo (150 palabras).\n2. Antecedentes y estado del arte.\n3. Problema a resolver y pertinencia.\n4. Objetivos y metodología.\n5. Impactos esperados (C1, C2, C3).\n6. Cronograma y entregables.\n7. Presupuesto desglosado.\n8. Currículum del equipo.', tags: { componente: 'C1', tipo: 'redaccion', dificultad: 'avanzado' } },
        { titulo: 'Cartas de apoyo y colaboración', prompt: 'Redacta una carta de apoyo institucional para mi proyecto:\n\nProyecto: [TÍTULO]\nInstitución solicitante: [INSTITUCIÓN]\nInstitución que apoya: [NOMBRE]\n\nElementos:\n1. Encabezado oficial.\n2. Manifestación de interés en el proyecto.\n3. Recursos que aporta la institución (espacio, equipos, personal).\n4. Compromiso de participación.\n5. Datos de contacto del responsable.\n6. Formato para firma y sello.', tags: { componente: 'C1', tipo: 'gestion', dificultad: 'basico' } },
        { titulo: 'Reporte técnico para informe financiero', prompt: 'Genera un reporte técnico para informe de finiquito de proyecto:\n\nTítulo del proyecto: [TÍTULO]\nNo. de registro: [REGISTRO]\nPeriodo: [INICIO - FIN]\n\nIncluye:\n1. Resumen de actividades realizadas contra plan original.\n2. Tabla de productos generados (artículos, tesis, informes, patentes).\n3. Evidencias de cada producto.\n4. Vinculación con componentes SNII (C1, C2, C3).\n5. Desviaciones y justificaciones.\n6. Impacto académico y social.\n7. Anexos con soporte documental.', tags: { componente: 'C1', tipo: 'gestion', dificultad: 'intermedio' } },
        { titulo: 'Identificación de convocatorias activas', prompt: 'Eres gestor de financiamiento científico. Ayúdame a identificar las mejores fuentes de financiamiento para:\n\nPerfil: [' + escape(p ? p.perfilInvestigacion || '[PERFIL]' : '[PERFIL]') + ']\nÁrea: [' + escape(p ? p.area || '[ÁREA]' : '[ÁREA]') + ']\nTipo de proyecto: [INVESTIGACIÓN BÁSICA / INNOVACIÓN / VINCULACIÓN / FORTALECIMIENTO]\n\nGenera:\n1. Mapa de convocatorias por tipo (SECIHTI, CONAHCYT, sectorial, internacional).\n2. Calendario anual de fechas típicas.\n3. Criterios de elegibilidad por convocatoria.\n4. Requisitos documentales comunes.\n5. Estrategia para armar un expediente de postulación reutilizable.', tags: { componente: 'C1', tipo: 'planificacion', dificultad: 'basico' } },
        { titulo: 'Justificación presupuestal detallada', prompt: 'Eres administrador de proyectos de investigación. Ayúdame a justificar el presupuesto de:\n\nProyecto: [TÍTULO]\nMonto total: [MONTO]\nRubros: [EQUIPO / VIAJES / MATERIALES / RECURSOS HUMANOS / PUBLICACIÓN OA]\n\nPara cada rubro incluye:\n1. Descripción detallada del gasto.\n2. Vinculación directa con objetivos del proyecto.\n3. Cotización o estimación de mercado.\n4. Justificación de costos en el contexto del área.\n5. Relación beneficio-costo para el desarrollo del proyecto.', tags: { componente: 'C1', tipo: 'gestion', dificultad: 'intermedio' } },
        { titulo: 'Cronograma financiero y ministraciones', prompt: 'Eres administrador financiero de proyectos académicos. Diseña un calendario de ministraciones para:\n\nProyecto: [TÍTULO]\nPresupuesto total: [MONTO]\nDuración: [MESES]\nFuente: [SECIHTI / CONAHCYT / INTERNO / INTERNACIONAL]\n\nIncluye:\n1. Calendarización de ingresos por período.\n2. Plan de gastos por trimestre alineado a actividades.\n3. Fechas de informes financieros parciales.\n4. Estrategia de comprobación y rendición de cuentas.\n5. Fondo de contingencia (5% del presupuesto).', tags: { componente: 'general', tipo: 'planificacion', dificultad: 'intermedio' } }
      ]},
      { nombre: 'Evaluación y métricas', icon: '📈', prompts: [
        { titulo: 'Análisis de citas y métricas', prompt: 'Analiza el impacto de mi producción académica:\n\n' + (function(){ try { return SICP.db.getProductos().slice(0,5).map(function(pr){ return '- ' + escape(pr.titulo) + ' (' + (pr.anno||'s/f') + ')'; }).join('\n'); } catch(e){ return '[LISTA TUS 5 PRODUCTOS PRINCIPALES]'; } })() + '\n\nPara cada producto, sugiere:\n1. Índice de citas esperado por campo.\n2. Cuartil JCR/SJR probable.\n3. Altmetrics potenciales (menciones en redes, políticas públicas, medios).\n4. Estrategia para aumentar citabilidad (fechas, preprint, redes).\n5. Identificar tus 3 productos con mayor potencial de impacto.', tags: { componente: 'C1', tipo: 'analisis', dificultad: 'intermedio' } },
        { titulo: 'Comparativa con pares por área', prompt: 'Actúa como analista de benchmarks académicos. Con base en mi producción:\n\nÁrea: [' + escape(p ? p.area || '[ÁREA]' : '[ÁREA]') + ']\nPerfil: [' + escape(p ? p.perfilInvestigacion || '[PERFIL]' : '[PERFIL]') + ']\nNivel: [' + escape(p ? p.nivelActual || '[NIVEL]' : '[NIVEL]') + ']\n\n' + (function(){ try { var pros = SICP.db.getProductos(); if(pros.length===0) return 'Productos: [LISTA]'; return 'Artículos: ' + pros.filter(function(pr){ return pr.tipo === 'Artículo'; }).length + ', Libros: ' + pros.filter(function(pr){ return pr.tipo === 'Libro'; }).length + ', Tesis: ' + pros.filter(function(pr){ return pr.tipo === 'Tesis'; }).length; } catch(e){ return 'Productos: [LISTA]'; } })() + '\n\nIndica:\n1. ¿Cómo me comparo con el perfil promedio para mi nivel?\n2. ¿En qué cuartil de productividad me encuentro?\n3. Fortalezas relativas (componentes destacados).\n4. Áreas de mejora competitiva.\n5. Meta recomendada para la siguiente evaluación.', tags: { componente: 'general', tipo: 'evaluacion', dificultad: 'intermedio' } },
        { titulo: 'Dashboard de indicadores SNII', prompt: 'Genera un dashboard de indicadores para monitorear mi avance hacia el SNII:\n\nIndicadores:\n- Score SNII: ' + (s ? s.scoreSNII + '%' : '[SCORE]') + '\n- Artículos: ' + (s ? s.articulos : '[N]') + ' / Meta: ' + (c ? c.metaArticulosAnual || 3 : 3) + '\n- Tesis: ' + (s ? s.tesis : '[N]') + ' / Meta: ' + (c ? c.metaTesisAnual || 2 : 2) + '\n- Liderazgo: ' + (s ? s.liderazgo : '[N]') + ' / Meta: ' + (c ? c.metaLiderazgoAnual || 2 : 2) + '\n- Divulgación: ' + (s ? s.divulgacion : '[N]') + ' / Meta: 2\n' + (s && s.brechas.length > 0 ? 'Brechas: ' + s.brechas.map(function(b) { return b.area; }).join(', ') : '') + '\n\nDiseña:\n1. Tablero visual con semáforos (🔴🟡🟢) por indicador.\n2. Tendencia trimestral recomendada.\n3. Acciones correctivas priorizadas por brecha.\n4. Proyección a 1 año si se mantiene el ritmo actual vs ritmo recomendado.', tags: { componente: 'general', tipo: 'analisis', dificultad: 'intermedio' } },
        { titulo: 'Análisis de fortalezas y debilidades SNII', prompt: 'Eres consultor estratégico para investigadores SNII. Realiza un análisis FODA de mi perfil:\n\nFortalezas:\n' + (function(){ try { var pros = SICP.db.getProductos(); var tipos = {}; pros.forEach(function(p){ tipos[p.tipo]=(tipos[p.tipo]||0)+1; }); return Object.keys(tipos).map(function(t){ return '- ' + t + ': ' + tipos[t]; }).join('\n') || '- [IDENTIFICA TUS FORTALEZAS]'; } catch(e){ return '- [IDENTIFICA TUS FORTALEZAS]'; } })() + '\n\nDebilidades: ' + (s && s.brechas.length > 0 ? s.brechas.map(function(b){ return b.area; }).join(', ') : '[IDENTIFICA TUS DEBILIDADES]') + '\n\nOportunidades futuras:\n- [CONVOCATORIAS, REDES, FORMACIÓN]\n\nAmenazas externas:\n- [COMPETENCIA, CAMBIOS NORMATIVOS]\n\nGenera:\n1. Matriz FODA completa.\n2. Estrategias FO (maxi-maxi), DO (mini-maxi), FA (maxi-mini), DA (mini-mini).\n3. Plan de acción con 3 prioridades estratégicas.', tags: { componente: 'general', tipo: 'evaluacion', dificultad: 'intermedio' } },
        { titulo: 'Proyección de crecimiento académico', prompt: 'Proyecta mi crecimiento académico a 3 años con base en:\n\nProducción actual:\n- Artículos: ' + (s ? s.articulos : '[N]') + ' en últimos 3 años\n- Tesis: ' + (s ? s.tesis : '[N]') + '\n- Proyectos: ' + (s ? s.proyectos : '[N]') + '\n\nMeta: [NIVEL SNII DESEADO]\n\nSimula 3 escenarios:\n1. Conservador: mantener ritmo actual.\n2. Moderado: +20% de productividad anual.\n3. Agresivo: +50% con colaboraciones internacionales.\n\nPara cada escenario: año estimado de meta alcanzada, score SNII proyectado, brechas remanentes.', tags: { componente: 'general', tipo: 'analisis', dificultad: 'avanzado' } }
      ]},
      { nombre: 'Bienestar y carrera académica', icon: '🧘', prompts: [
        { titulo: 'Plan de bienestar para investigador', prompt: 'Eres coach de productividad académica. Diseña un plan de bienestar para investigador que busca el SNII:\n\nSíntomas comunes: fatiga cognitiva, ansiedad por productividad, aislamiento social, síndrome del impostor.\n\nGenera:\n1. Rutina diaria con bloques de trabajo profundo (90 min) + pausas restaurativas.\n2. Técnicas anti-bloqueo de escritura (free writing, pomodoro inverso).\n3. Red de apoyo: mentores, pares, terapia académica.\n4. Indicadores de alerta (cuándo pedir ayuda).\n5. Plan de desconexión digital semanal.', tags: { componente: 'general', tipo: 'planificacion', dificultad: 'basico' } },
        { titulo: 'Hoja de ruta profesional 5 años', prompt: 'Diseña una hoja de ruta profesional a 5 años para:\n\nPosición actual: [' + escape(p ? (p.nombre || '[NOMBRE]') + ', ' + (p.institucion || '[INSTITUCIÓN]') : '[NOMBRE, INSTITUCIÓN]') + ']\nNivel SNII actual: [' + escape(p ? p.nivelActual || '[NIVEL]' : '[NIVEL]') + ']\n\nMetas a 5 años:\n- Meta SNII: [CANDIDATO / NIVEL I / II / III]\n- Productividad: [N] artículos/año, [N] libros, [N] tesis\n- Liderazgo: comités, redes, conferencias\n- Financiamiento: proyectos, estancias\n\nFormato: timeline año por año con hitos académicos, productos clave, y metas personales. Incluye plan B.', tags: { componente: 'general', tipo: 'planificacion', dificultad: 'intermedio' } },
        { titulo: 'Estrategia contra procrastinación', prompt: 'Eres terapeuta cognitivo-conductual especializado en procrastinación académica. Diseña un plan de 4 semanas:\n\nPerfil del investigador:\n- Área: [' + escape(p ? p.area || '[ÁREA]' : '[ÁREA]') + ']\n- Tareas que más postergo: [ESCRITURA / ANÁLISIS / LECTURA / GESTIÓN]\n\nSemana 1: Identificación de disparadores y auto-registro.\nSemana 2: Reestructuración cognitiva (perfeccionismo vs. avance).\nSemana 3: Implementación de micro-hábitos (regla de los 2 minutos).\nSemana 4: Evaluación y ajuste.\n\nIncluye ejercicios prácticos para cada semana.', tags: { componente: 'general', tipo: 'planificacion', dificultad: 'basico' } },
        { titulo: 'Técnicas de negociación académica', prompt: 'Eres mediador profesional especializado en entornos académicos. Ayúdame a preparar:\n\nSituación a negociar: [CARGA ACADÉMICA / SALARIO / RECURSOS / COLABORACIÓN / AUTORÍA]\nContraparte: [DIRECTOR / COLEGA / INSTITUCIÓN / EDITOR]\nMi posición: [QUÉ QUIERO Y POR QUÉ]\n\nGenera:\n1. Mapa de intereses (qué quiere cada parte).\n2. BATNA (mejor alternativa a un acuerdo negociado).\n3. Argumentos basados en datos (productividad, impacto, carga).\n4. Frases clave para la conversación.\n5. Escenario de contraoferta y cómo responder.', tags: { componente: 'general', tipo: 'presentacion', dificultad: 'avanzado' } },
        { titulo: 'Plan de transición de carrera', prompt: 'Eres mentor de carrera académica. Ayúdame a diseñar una transición profesional:\n\nEtapa actual: [ESTUDIANTE POSGRADO / POSDOC / INVESTIGADOR / PROFESOR]\nEtapa deseada: [POSDOC / INVESTIGADOR TITULAR / SNII / INDUSTRIA]\nTiempo estimado: [AÑOS]\n\nIncluye:\n1. Brecha de competencias actual vs. deseada.\n2. Portafolio de evidencias para la transición.\n3. Estrategia de networking y mentores.\n4. Posibles obstáculos y cómo superarlos.\n5. Plan financiero para la transición.\n6. Indicadores de éxito por etapa.', tags: { componente: 'general', tipo: 'planificacion', dificultad: 'intermedio' } },
        { titulo: 'Prevención del síndrome de burnout', prompt: 'Eres psicólogo especializado en salud mental de académicos. Diseña un plan de prevención de burnout:\n\nSíntomas actuales: [FATIGA / INSOMNIO / IRRITABILIDAD / FALTA DE MOTIVACIÓN]\nCarga semanal: [HORAS]\nPlazos próximos: [FECHAS IMPORTANTES]\n\nDiagnóstico:\n1. Nivel de agotamiento emocional estimado (bajo, medio, alto).\n2. Principales factores estresantes identificados.\n3. Evaluación de equilibrio trabajo-vida personal.\n\nPlan de intervención:\n1. Micro-pausas diarias (técnica 52-17).\n2. Límites firmes (horarios de trabajo definidos).\n3. Actividades restaurativas obligatorias.\n4. Red de apoyo institucional.\n5. Señales de alarma para buscar ayuda profesional.', tags: { componente: 'general', tipo: 'planificacion', dificultad: 'basico' } }
      ]}
    ];
  }

  function getTags(t) {
    return t.tags || { componente: 'general', tipo: 'planificacion', dificultad: 'basico' };
  }

  function renderPromptCard(promptObj, idx, urgente) {
    var tags = getTags(promptObj);
    var labelComp = { C1: '🔵 C1', C2: '🟠 C2', C3: '🟢 C3', general: '⚪ General' }[tags.componente] || '⚪';
    var labelDificultad = { basico: '🟢', intermedio: '🟡', avanzado: '🔴' }[tags.dificultad] || '🟢';
    var labelTipo = { redaccion: '✍️', analisis: '📊', planificacion: '📋', gestion: '⚙️', evaluacion: '📈', creatividad: '💡', presentacion: '🎤' }[tags.tipo] || '📌';

    return '<div class="prompt-card' + (urgente ? ' urgent' : '') + '">' +
      '<div style="display:flex;justify-content:space-between;align-items:start;gap:8px;flex-wrap:wrap">' +
        '<h4>' + promptObj.titulo + '</h4>' +
        '<div class="flex gap-8" style="flex-wrap:wrap">' +
          '<span style="font-size:.65rem;padding:1px 6px;border-radius:4px;background:var(--surface2);border:1px solid var(--line)" title="Componente">' + labelComp + '</span>' +
          '<span style="font-size:.65rem;padding:1px 6px;border-radius:4px;background:var(--surface2);border:1px solid var(--line)" title="Tipo">' + labelTipo + '</span>' +
          '<span style="font-size:.65rem;padding:1px 6px;border-radius:4px;background:var(--surface2);border:1px solid var(--line)" title="Dificultad">' + labelDificultad + ' ' + tags.dificultad + '</span>' +
        '</div>' +
      '</div>' +
      '<textarea readonly onclick="this.select()" rows="5" style="font-size:.78rem;margin-top:8px">' + escape(promptObj.prompt) + '</textarea>' +
      '<div class="flex gap-8 mt-8"><button class="btn btn-sm btn-accent" onclick="SICP.IAModule.copiarPrompt(this)">📋 Copiar</button>' +
      '<button class="btn btn-sm btn-secondary" onclick="SICP.IAModule.usarPersonalizado(this)">✏️ Personalizar</button></div></div>';
  }

  function filtrarInteligente(categorias, datos) {
    var search = _search.toLowerCase().trim();
    var comp = _filtroComponente;
    var dif = _filtroDificultad;
    var tipo = _filtroTipo;
    var smart = _smartFilter;

    var brechas = (datos && datos.stats) ? datos.stats.brechas || [] : [];
    var brechasComp = {};
    brechas.forEach(function(b) {
      var c = b.area.indexOf('C1') !== -1 ? 'C1' : b.area.indexOf('C2') !== -1 ? 'C2' : b.area.indexOf('C3') !== -1 ? 'C3' : '';
      if (c) brechasComp[c] = (brechasComp[c] || 0) + 1;
    });

    var totalBrechas = Object.keys(brechasComp).length > 0;

    return categorias.map(function(cat) {
      var promptsFiltrados = cat.prompts.filter(function(p) {
        var t = getTags(p);
        if (comp && t.componente !== comp) return false;
        if (dif && t.dificultad !== dif) return false;
        if (tipo && t.tipo !== tipo) return false;
        if (search && p.titulo.toLowerCase().indexOf(search) === -1 && p.prompt.toLowerCase().indexOf(search) === -1 && cat.nombre.toLowerCase().indexOf(search) === -1) return false;
        return true;
      });

      if (smart && totalBrechas) {
        promptsFiltrados = promptsFiltrados.slice().sort(function(a, b) {
          var ta = getTags(a), tb = getTags(b);
          return (brechasComp[tb.componente] || 0) - (brechasComp[ta.componente] || 0);
        });
      }

      if (smart) {
        promptsFiltrados.forEach(function(p) { p._urgente = brechasComp[getTags(p).componente] > 0; });
      }

      return { cat: cat, prompts: promptsFiltrados };
    }).filter(function(item) { return item.prompts.length > 0; });
  }

  function _copiarTexto(text, btn) {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(text).then(function() {
        if (btn) { btn.textContent = '✅ Copiado'; setTimeout(function() { btn.textContent = '📋 Copiar'; }, 2000); }
      }).catch(function() { _fallbackCopyText(text, btn); });
    } else {
      _fallbackCopyText(text, btn);
    }
  }

  function _fallbackCopyText(text, btn) {
    var ta = document.createElement('textarea');
    ta.value = text;
    ta.style.position = 'fixed';
    ta.style.opacity = '0';
    document.body.appendChild(ta);
    ta.select();
    try { document.execCommand('copy'); if (btn) { btn.textContent = '✅ Copiado'; setTimeout(function() { btn.textContent = '📋 Copiar'; }, 2000); } } catch(e) {}
    document.body.removeChild(ta);
  }

  return {
    _copiarTexto: _copiarTexto,
    copiarPrompt: function(btn) {
      var textarea = btn.closest('.prompt-card').querySelector('textarea');
      _copiarTexto(textarea.value, btn);
    },

    usarPersonalizado: function(btn) {
      var card = btn.closest('.prompt-card');
      var textarea = card.querySelector('textarea');
      var titulo = card.querySelector('h4').textContent;
      var datos = getPerfil();
      var ctx = {
        TEMA: '[ingresa tu tema]',
        NOMBRE: datos && datos.perfil ? datos.perfil.nombre || '[tu nombre]' : '[tu nombre]',
        AREA: datos && datos.perfil ? datos.perfil.area || '[tu área SNII]' : '[tu área SNII]',
        PERFIL: datos && datos.perfil ? datos.perfil.perfilInvestigacion || '[tu perfil]' : '[tu perfil]',
        NIVEL: datos && datos.perfil ? datos.perfil.nivelActual || '[tu nivel]' : '[tu nivel]',
        SCORE: datos && datos.stats ? datos.stats.scoreSNII + '%' : '[tu score]'
      };
      SICP.modal.showModal('✏️ Personalizar: ' + titulo,
        '<div class="form-group"><label>Prompt original</label><textarea class="form-control" readonly rows="5">' + escape(textarea.value) + '</textarea></div>' +
        '<div style="background:#f0fdf4;border-radius:8px;padding:12px;margin-bottom:12px"><strong style="color:var(--ok)">✅ Datos detectados de tu perfil</strong><ul style="font-size:.82rem;margin-top:8px;padding-left:16px">' +
        Object.keys(ctx).map(function(k) { return '<li><strong>' + k + '</strong> → ' + ctx[k] + '</li>'; }).join('') + '</ul></div>' +
        '<div class="form-group"><label>Tu prompt personalizado</label><textarea class="form-control" id="prompt-personalizado" rows="8" style="font-size:.78rem">' +
        textarea.value.replace(/\[TEMA\]/g, ctx.TEMA).replace(/\[NOMBRE\]/g, ctx.NOMBRE).replace(/\[ÁREA\]/g, ctx.AREA).replace(/\[PERFIL\]/g, ctx.PERFIL).replace(/\[NIVEL\]/g, ctx.NIVEL) +
        '</textarea></div>' +
        '<button class="btn btn-primary" onclick="SICP.IAModule._copiarTexto(document.getElementById(\'prompt-personalizado\').value,this)">📋 Copiar prompt personalizado</button>'
      );
    },

    cambiarFiltro: function(tipo, valor) {
      if (tipo === 'search') { _search = valor; }
      else if (tipo === 'componente') { _filtroComponente = (_filtroComponente === valor) ? '' : valor; }
      else if (tipo === 'dificultad') { _filtroDificultad = (_filtroDificultad === valor) ? '' : valor; }
      else if (tipo === 'tipo') { _filtroTipo = (_filtroTipo === valor) ? '' : valor; }
      else if (tipo === 'smart') { _smartFilter = !_smartFilter; }
      if (window.SICP_APP) SICP_APP.refresh();
    },

    render: function() {
      var datos = getPerfil();
      var categorias = getCategorias(datos);
      var totalPrompts = categorias.reduce(function(sum, cat) { return sum + cat.prompts.length; }, 0);

      var filtrados = filtrarInteligente(categorias, datos);
      var countFiltrados = filtrados.reduce(function(s, i) { return s + i.prompts.length; }, 0);

      var isActive = function(t, v) {
        if (t === 'componente') return _filtroComponente === v ? 'btn-primary' : 'btn-sm';
        if (t === 'dificultad') return _filtroDificultad === v ? 'btn-primary' : 'btn-sm';
        if (t === 'tipo') return _filtroTipo === v ? 'btn-primary' : 'btn-sm';
        if (t === 'smart') return _smartFilter ? 'btn-primary' : 'btn-sm';
        return 'btn-sm';
      };

      var categoriasHtml = filtrados.map(function(item) {
        var cat = item.cat;
        return '<div class="card"><h3 class="mb-8">' + cat.icon + ' ' + cat.nombre + ' <span class="text-sm text-muted" style="font-weight:400">(' + item.prompts.length + ' prompts)</span></h3><div class="grid grid-2">' +
          item.prompts.map(function(p, i) { return renderPromptCard(p, i, p._urgente); }).join('') + '</div></div>';
      }).join('') || '<div class="card"><div class="empty-state"><p class="text-muted">😕 Ningún prompt coincide con los filtros seleccionados.</p><button class="btn btn-sm mt-8" onclick="SICP.IAModule.limpiarFiltros()">Limpiar filtros</button></div></div>';

      return '<div class="card"><div class="card-header"><h2>🧠 Biblioteca de IA + Prompts Estratégicos</h2></div>' +
        '<div class="flex-between mb-16"><p class="text-muted">' + totalPrompts + ' prompts — <strong>' + countFiltrados + '</strong> mostrados</p>' +
        (datos && datos.perfil && datos.perfil.nombre ? '<span class="badge ok" style="font-size:.75rem">👤 ' + escape(datos.perfil.nombre) + ' · Score SNII: ' + (datos.stats ? datos.stats.scoreSNII + '%' : '—') + '</span>' : '') +
        '</div>' +
        '<div class="note" style="background:#fffbeb;border:1px solid #fde68a;border-radius:12px;padding:14px;color:#78350f"><strong>⚠️ Uso ético:</strong> La IA debe ser una herramienta de apoyo. Revisa, verifica y adapta siempre los resultados.</div></div>' +

        '<div class="card mb-16"><div class="flex gap-8 items-center" style="padding:8px 0">' +
          '<span>🔍</span><input class="form-control" id="ia-search" placeholder="Buscar por palabra clave…" value="' + escape(_search) + '" oninput="SICP.IAModule.cambiarFiltro(\'search\',this.value)" style="flex:1">' +
          '<span class="text-sm text-muted">' + countFiltrados + ' prompts</span>' +
        '</div>' +

        '<div class="flex gap-8" style="padding:4px 0;flex-wrap:wrap;border-top:1px solid var(--line);padding-top:8px">' +
          '<span class="text-sm font-bold" style="min-width:90px">Componente:</span>' +
          COMPONENTES.map(function(c) { return '<button class="btn ' + isActive('componente', c) + '" onclick="SICP.IAModule.cambiarFiltro(\'componente\',\'' + c + '\')">' + ({ C1: '🔵 C1', C2: '🟠 C2', C3: '🟢 C3', general: '⚪ Todo' })[c] + '</button>'; }).join('') +
        '</div>' +

        '<div class="flex gap-8" style="padding:4px 0;flex-wrap:wrap">' +
          '<span class="text-sm font-bold" style="min-width:90px">Dificultad:</span>' +
          DIFICULTADES.map(function(d) { return '<button class="btn ' + isActive('dificultad', d) + '" onclick="SICP.IAModule.cambiarFiltro(\'dificultad\',\'' + d + '\')">' + ({ basico: '🟢 Básico', intermedio: '🟡 Intermedio', avanzado: '🔴 Avanzado' })[d] + '</button>'; }).join('') +
        '</div>' +

        '<div class="flex gap-8" style="padding:4px 0;flex-wrap:wrap">' +
          '<span class="text-sm font-bold" style="min-width:90px">Tipo:</span>' +
          TIPOS.map(function(t) { return '<button class="btn ' + isActive('tipo', t) + '" onclick="SICP.IAModule.cambiarFiltro(\'tipo\',\'' + t + '\')">' + ({ redaccion: '✍️ Redacción', analisis: '📊 Análisis', planificacion: '📋 Planificación', gestion: '⚙️ Gestión', evaluacion: '📈 Evaluación', creatividad: '💡 Creatividad', presentacion: '🎤 Presentación' })[t] + '</button>'; }).join('') +
        '</div>' +

        '<div class="flex gap-8" style="padding:4px 0;flex-wrap:wrap;border-top:1px solid var(--line);margin-top:4px;padding-top:8px">' +
          '<button class="btn ' + isActive('smart', true) + '" onclick="SICP.IAModule.cambiarFiltro(\'smart\',true)" title="Prioriza prompts según tus brechas detectadas">🤖 Filtro inteligente ' + (_smartFilter ? 'activado' : '') + '</button>' +
          (datos && datos.stats && datos.stats.brechas.length > 0 ? '<span class="text-sm text-muted" style="font-style:italic">Priorizando: ' + datos.stats.brechas.map(function(b){ return b.area; }).join(', ') + '</span>' : '') +
        '</div></div>' +

        categoriasHtml +

        '<div class="card mt-16"><h3 class="mb-8">💡 Cómo usar los prompts</h3>' +
        '<div class="grid grid-3" style="font-size:.85rem">' +
          '<div style="padding:12px;background:var(--surface2);border-radius:8px;text-align:center"><div style="font-size:1.5rem">1️⃣</div><strong>Filtra</strong><p class="text-sm text-muted">Usa los filtros por componente, dificultad o el filtro inteligente que prioriza tus brechas.</p></div>' +
          '<div style="padding:12px;background:var(--surface2);border-radius:8px;text-align:center"><div style="font-size:1.5rem">2️⃣</div><strong>Personaliza</strong><p class="text-sm text-muted">Cada prompt tiene datos de tu perfil inyectados. Usa ✏️ para ajustarlos.</p></div>' +
          '<div style="padding:12px;background:var(--surface2);border-radius:8px;text-align:center"><div style="font-size:1.5rem">3️⃣</div><strong>Copia y pega</strong><p class="text-sm text-muted">Pega en ChatGPT, Claude o Gemini. Revisa y adapta siempre el resultado.</p></div>' +
        '</div></div>';
    },

    limpiarFiltros: function() {
      _search = ''; _filtroComponente = ''; _filtroDificultad = ''; _filtroTipo = ''; _smartFilter = false;
      if (window.SICP_APP) SICP_APP.refresh();
    },

    afterRender: function() {
      if (_search) {
        var input = document.getElementById('ia-search');
        if (input) { input.value = _search; var len = _search.length; input.setSelectionRange(len, len); input.focus(); }
      }
    }
  };
})();
